# -*- coding: utf-8 -*-
"""HTML_quick_Styler_Generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prGaSIkUnU2BU6L3Xo7fL0nuxvMCAV1m
"""

import gradio as gr


# -------- HTML GENERATOR --------

def generate_page(title, description):

    html = f"""
<!DOCTYPE html>
<html>
<head>

<title>{title}</title>

<style>

body {{
font-family: Arial;
margin:0;
background:#f5f5f5;
}}

header {{
background:linear-gradient(90deg,#4facfe,#00f2fe);
color:white;
text-align:center;
padding:60px;
}}

section {{
background:white;
margin:20px;
padding:30px;
border-radius:10px;
box-shadow:0 4px 10px rgba(0,0,0,0.1);
}}

.grid {{
display:grid;
grid-template-columns:repeat(auto-fit,minmax(200px,1fr));
gap:20px;
}}

.card {{
background:#fafafa;
padding:20px;
border-radius:8px;
text-align:center;
}}

footer {{
background:#222;
color:white;
text-align:center;
padding:20px;
}}

</style>

</head>

<body>

<header>
<h1>{title}</h1>
<p>{description}</p>
</header>

<section>
<h2>About</h2>
<p>This website is created using Smart Web Layout Generator.</p>
</section>

<section>

<h2>Services</h2>

<div class="grid">

<div class="card">
<h3>Service 1</h3>
<p>Feature description</p>
</div>

<div class="card">
<h3>Service 2</h3>
<p>Feature description</p>
</div>

<div class="card">
<h3>Service 3</h3>
<p>Feature description</p>
</div>

</div>

</section>

<section>
<h2>Contact</h2>
<p>Email : example@email.com</p>
</section>

<footer>
<p>© 2026 {title}</p>
</footer>

</body>
</html>
"""

    return html


def preview_page(code):
    return code


# -------- COLOR PALETTES --------

def show_palette():

    return """
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:20px">

<div style="padding:20px;border-radius:10px;background:white;box-shadow:0 4px 10px rgba(0,0,0,0.1)">
<h3>Modern</h3>
<div style="height:30px;background:#4facfe"></div>
<div style="height:30px;background:#00f2fe"></div>
<p>Primary : #4facfe</p>
<p>Secondary : #00f2fe</p>
<p>Background : #f5f5f5</p>
</div>

<div style="padding:20px;border-radius:10px;background:white;box-shadow:0 4px 10px rgba(0,0,0,0.1)">
<h3>Ocean</h3>
<div style="height:30px;background:#2193b0"></div>
<div style="height:30px;background:#6dd5ed"></div>
<p>Primary : #2193b0</p>
<p>Secondary : #6dd5ed</p>
<p>Background : #e0f7fa</p>
</div>

<div style="padding:20px;border-radius:10px;background:white;box-shadow:0 4px 10px rgba(0,0,0,0.1)">
<h3>Sunset</h3>
<div style="height:30px;background:#ff7e5f"></div>
<div style="height:30px;background:#feb47b"></div>
<p>Primary : #ff7e5f</p>
<p>Secondary : #feb47b</p>
<p>Background : #fff3e0</p>
</div>

<div style="padding:20px;border-radius:10px;background:white;box-shadow:0 4px 10px rgba(0,0,0,0.1)">
<h3>Forest</h3>
<div style="height:30px;background:#134e5e"></div>
<div style="height:30px;background:#71b280"></div>
<p>Primary : #134e5e</p>
<p>Secondary : #71b280</p>
<p>Background : #e8f5e9</p>
</div>

</div>
"""


# -------- TEMPLATE INFO --------

def template_info():

    return """
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:20px">

<div style="padding:20px;background:white;border-radius:10px;box-shadow:0 4px 10px rgba(0,0,0,0.1)">
<h3>Blog Template</h3>
<ul>
<li>Hero</li>
<li>About</li>
<li>Blog Posts</li>
<li>Contact</li>
</ul>
</div>

<div style="padding:20px;background:white;border-radius:10px;box-shadow:0 4px 10px rgba(0,0,0,0.1)">
<h3>Startup Landing Page</h3>
<ul>
<li>Hero Banner</li>
<li>Features</li>
<li>Pricing</li>
<li>Testimonials</li>
</ul>
</div>

<div style="padding:20px;background:white;border-radius:10px;box-shadow:0 4px 10px rgba(0,0,0,0.1)">
<h3>Agency Website</h3>
<ul>
<li>Hero</li>
<li>Services</li>
<li>Portfolio</li>
<li>Team</li>
</ul>
</div>

<div style="padding:20px;background:white;border-radius:10px;box-shadow:0 4px 10px rgba(0,0,0,0.1)">
<h3>Portfolio Website</h3>
<ul>
<li>Hero</li>
<li>About Me</li>
<li>Projects</li>
<li>Skills</li>
</ul>
</div>

</div>
"""


# -------- GUIDE --------

def guide():

    return """
<div style="background:white;padding:30px;border-radius:10px;box-shadow:0 4px 10px rgba(0,0,0,0.1)">

<h2>How to Use Smart Web Layout Generator</h2>

<ol style="line-height:2">

<li>Enter Website Title</li>
<li>Enter Description</li>
<li>Click Generate Page</li>
<li>HTML Code will appear</li>
<li>Open Live Preview tab</li>
<li>Click Load Preview</li>
<li>Your website will appear instantly</li>

</ol>

</div>
"""


# -------- UI --------

with gr.Blocks() as demo:

    gr.Markdown("# Smart Web Layout Generator")

    with gr.Tabs():

        with gr.Tab("Generate Page"):

            title = gr.Textbox(label="Website Title")
            description = gr.Textbox(label="Website Description")

            generate_btn = gr.Button("Generate Page")

            html_code = gr.Textbox(lines=20,label="Generated HTML Code")

            generate_btn.click(
                generate_page,
                inputs=[title,description],
                outputs=html_code
            )


        with gr.Tab("Live Preview"):

            preview_btn = gr.Button("Load Preview")

            preview_area = gr.HTML()

            preview_btn.click(
                preview_page,
                inputs=html_code,
                outputs=preview_area
            )


        with gr.Tab("Color Palettes"):

            palette_btn = gr.Button("Show Color Palettes")

            palette_output = gr.HTML()

            palette_btn.click(
                show_palette,
                outputs=palette_output
            )


        with gr.Tab("Templates"):

            template_btn = gr.Button("Show Templates")

            template_output = gr.HTML()

            template_btn.click(
                template_info,
                outputs=template_output
            )


        with gr.Tab("Guide"):

            guide_btn = gr.Button("Show Guide")

            guide_output = gr.HTML()

            guide_btn.click(
                guide,
                outputs=guide_output
            )


demo.launch()